Add pagination to requests and discussions, improve message
umbrellio/gbot pull request #1
Opened 2020-10-08 11:51 UTC by JustSnow

### Summary
* Added pagination. Now we able to fetch all possible requests and discussions for single request
* Improved message. Added authors of unresolved threads for request

2020-10-08 14:54 UTC, nulldef requested changes

2020-10-08 14:54 UTC, nulldef commented on api/gitlab.js
> +      while (totalPages !== undefined && parseInt(totalPages) > page) {
К инту приводить лучше сразу при объявлении.

2020-10-08 14:54 UTC, nulldef commented on api/gitlab.js
> +  getPaginated = (uri, query = {}) => {
Это наверное приватный метод?

2020-10-08 14:54 UTC, nulldef commented on api/gitlab.js
> +      let { headers } = results
А почему не `const` везде?

2020-10-08 14:54 UTC, nulldef commented on api/gitlab.js
> +      while (totalPages !== undefined && parseInt(totalPages) > page) {
`totalPages` скорее будет `null`, чем `undefined`

2020-10-08 14:54 UTC, nulldef commented on gbot
> +const Unapproved = require("./tasks/unapproved")
Может лучше тогда файл переименовать?

2020-10-08 14:54 UTC, nulldef commented on tasks/BaseCommand.js
> +const GitLab = require("../api/gitlab")
А тут почему с маленькой стало? 🤔

2020-10-08 14:54 UTC, nulldef commented on tasks/unapproved.js
> +    const unresolvedAuthors = this.__unresolvedAuthorsFor(request).map(author => {
Давай это лучше выше вынесем, под `const reaction = this.__getEmoji(updated)`. Чтобы отделить сборку строк от логики.

2020-10-08 14:54 UTC, nulldef commented on tasks/unapproved.js
> +      message.push(`approved by: ${approvedBy}`)
Я бы добавил `already approved by ...`, чтобы более зазывающе было )

2020-10-08 14:54 UTC, nulldef commented on tasks/unapproved.js
> +    if (!_.isEmpty(unresolvedAuthors)) {
Условия лучше читаются, когда написаны в "положительную" сторону. Можно сделать хелпер типа `isPresent` или вот так
```js
if (unresolvedAuthors.length > 0) {
```

2020-10-08 14:54 UTC, nulldef commented on tasks/unapproved.js
> +      message.push(`unresolved threads: ${unresolvedAuthors}`)
`unresolved threads by ${unresolvedAuthors}` может?

2020-10-08 15:05 UTC, JustSnow commented on api/gitlab.js
> +  getPaginated = (uri, query = {}) => {
не обязательно, но можно сделать и исключительно приватным

2020-10-08 15:07 UTC, JustSnow commented on api/gitlab.js
> +      while (totalPages !== undefined && parseInt(totalPages) > page) {
в случае, если нету такого хэдера, то будет undefined. А вот если нечего пагинировать то будет `1`

2020-10-08 15:07 UTC, nulldef commented on api/gitlab.js
> +  getPaginated = (uri, query = {}) => {
Ну он довольно приватно выглядит, я бы не хотел его шарить)

2020-10-08 15:10 UTC, nulldef commented on api/gitlab.js
> +      while (totalPages !== undefined && parseInt(totalPages) > page) {
Можно еще вот так
```js
const totalPages = parseInt(headers['x-total-pages']) || 1
```

и уже останется только 1 условие здесь

2020-10-08 15:10 UTC, basherru commented on api/gitlab.js
> +      let totalPages = headers['x-total-pages']
тут везде кста двойные кавычки юзаются)

2020-10-08 15:14 UTC, tycooon commented on api/gitlab.js
> +      let totalPages = headers['x-total-pages']
Странно, что линтеру норм 🤔

2020-10-08 15:15 UTC, nulldef commented on api/gitlab.js
> +      let totalPages = headers['x-total-pages']
Кстати да

2020-10-08 15:15 UTC, JustSnow commented on tasks/BaseCommand.js
> +const GitLab = require("../api/gitlab")
потому что файл так называется) до этого не ругалось вообще на это. Только столкнулся, когда стал тестить сборку прям с гита

2020-10-09 08:55 UTC, nulldef commented on tasks/BaseCommand.js
> +const GitLab = require("../api/gitlab")
Странно, у меня на ноуте он с большой 🤔 
Давай с заглавной сделаем, это же класс, как-никак)

2020-10-09 08:55 UTC, nulldef commented on tasks/Unapproved.js
> +  __unresolvedAuthors = (request) => {
- `__unresolvedAuthorsString` лучше, иначе как будто возвращаются сами авторы
- и скобки, по идее, не нужны, опять линтер почему то не ругается

2020-10-09 08:57 UTC, JustSnow commented on tasks/Unapproved.js
> +  __unresolvedAuthors = (request) => {
```
➜ yarn eslint
yarn run v1.22.4
$ /Users/asolomkin/personal-projects/gbot/node_modules/.bin/eslint
✨  Done in 0.69s.
```

2020-10-09 08:59 UTC, JustSnow commented
@nulldef по поводу того, что файл на ноуте с большой. Сегодня столкнулся с этим. На маке гит не подхватывает изменения регистара букв в файле. Надо явно гитом делать, чтобы корректно было `git mv`

2020-10-09 09:22 UTC, JustSnow commented on tasks/BaseCommand.js
> +const GitLab = require("../api/gitlab")
@nulldef по поводу того, что файл на ноуте с большой. Сегодня столкнулся с этим. На маке гит не подхватывает изменения регистара букв в файле. Надо явно гитом делать, чтобы корректно было git mv

2020-10-09 09:27 UTC, nulldef commented on tasks/Unapproved.js
> +  __unresolvedAuthors = (request) => {
В общем, запушил фиксы линтера, теперь должен ругаться

2020-10-09 11:24 UTC, nulldef approved these changes

2020-10-09 11:30 UTC, nulldef commented
Подмержишь мастер? Там линтер пофикшен.

2020-10-09 11:32 UTC, JustSnow commented
@nulldef да, уже подмержил и все поправил :)

2020-10-09 11:36 UTC, merged