Add ability to control approved by tagging
umbrellio/gbot pull request #2
Opened 2020-10-14 12:15 UTC by JustSnow

Added setting to control `approved by` authors tagging.

2020-10-14 12:32 UTC, nulldef requested changes

2020-10-14 12:32 UTC, nulldef commented on tasks/BaseCommand.js
> +  __getConfigSetting = (settingName, defaultValue = {}) => {
Не стоит дефолтом делать объект, это не очевидно. Тут по хорошему должен быть `null`.

2020-10-14 12:32 UTC, nulldef commented on tasks/Unapproved.js
> +    this.emoji = this.__getConfigSetting("unapproved.emoji")
Мне кажется не стоит сеттить это прям в свойства класса, потому что
1. это конфигурация 
2. юзатеся только в одном месте

2020-10-14 12:32 UTC, nulldef commented on tasks/Unapproved.js
> +      let message = user.name
А почему тут `name`, а там `username`? 🤔

2020-10-14 12:43 UTC, JustSnow commented on tasks/Unapproved.js
> +    this.emoji = this.__getConfigSetting("unapproved.emoji")
я подумал, что лучше это вынести в конструктор, потому что будем вызывать один раз, а не как сейчас для каждого реквеста. Настройка то не меняется от реквеста к реквесту

2020-10-14 12:44 UTC, nulldef commented on tasks/Unapproved.js
> +    this.emoji = this.__getConfigSetting("unapproved.emoji")
А чем плохо брать каждый раз в этом случае?)

2020-10-14 12:45 UTC, JustSnow commented on tasks/Unapproved.js
> +      let message = user.name
`name` более официально, а по `username` можно тегать в чатике. Если не согласен, можно оставить только `username`

2020-10-14 12:49 UTC, JustSnow commented on tasks/Unapproved.js
> +    this.emoji = this.__getConfigSetting("unapproved.emoji")
я не говорю, что это плохо. Но зачем это делать каждый раз, если можно сделать один. Если настаиваешь, верну обратно и буду обращаться каждый раз к конфигу :)

2020-10-14 13:02 UTC, nulldef commented on tasks/Unapproved.js
> +      let message = user.name
Лучше придерживаться одного стиля, как мне кажется

2020-10-14 13:03 UTC, nulldef commented on tasks/Unapproved.js
> +    this.emoji = this.__getConfigSetting("unapproved.emoji")
Это же не свойства этой команды, а конфиг отдельно взятых частей. Так что да, давай пусть будет там, где используется)

2020-10-15 07:50 UTC, nulldef commented on tasks/unapproved/UnapprovedRequestDescription.js
> +      return this.__wrapString(`@${user.username}`, !tagApprovedBy)
Ну не, условие должно остаться тут, функция только оборачивает строку. Кстати, ее можно вынести вообще из класса наверх или в утилиты какие нибудь.

2020-10-15 07:50 UTC, nulldef commented on gbot.example.yml
> +    approved_by: false
Я бы назвал их `approvers`, чтобы покрасивее выглядело)

2020-10-15 07:50 UTC, nulldef commented on tasks/unapproved/UnapprovedRequestDescription.js
> +class UnapprovedRequestDescription {
Кстати не обязательно было делать это классом, можно было просто функцией, но как знаешь)

2020-10-15 07:55 UTC, JustSnow commented on tasks/unapproved/UnapprovedRequestDescription.js
> +class UnapprovedRequestDescription {
вынес в класс, чтобы инкапсулировать логику по формированию сообщения и не засорять всякими проверками основной класс по unapproved команде

2020-10-15 07:56 UTC, JustSnow commented on tasks/unapproved/UnapprovedRequestDescription.js
> +      return this.__wrapString(`@${user.username}`, !tagApprovedBy)
спасибо, поправлю

2020-10-15 08:15 UTC, nulldef commented on tasks/unapproved/UnapprovedRequestDescription.js
> +class UnapprovedRequestDescription {
Я понимаю, я имею в виду тоже отдельный файл, но просто не класс

2020-10-15 08:29 UTC, JustSnow commented on tasks/unapproved/UnapprovedRequestDescription.js
> +class UnapprovedRequestDescription {
мне показалось тут ООП подход) но если настаиваешь, могу просто файл и функцией сделать :)

2020-10-15 09:05 UTC, nulldef commented on tasks/unapproved/UnapprovedRequestDescription.js
> +class UnapprovedRequestDescription {
Не, я ж написал, как тебе удобнее)

2020-10-15 09:14 UTC, nulldef approved these changes

2020-10-15 09:14 UTC, merged